### ISSUE TITLE
How can my video auto responsive ?? EX: Video of Youtube

### ISSUE THREAD

**Issue by PhatDang** [feedmeastraycat/wp-editor-widget#14]
I have a link Youtube and i want to add my Home Content Page. It's appear, but when i Responsive this, it's not work. How can i do it ???

**Comment by feedmeastraycat** [comment]
Sorry for a late response.

Not sure this is plugin related but something for your css setup. The content is output using filters and pretty much the same way a regular post content would be printed.

**Comment by PhatDang** [comment]
Thanks, I did. :+1:
