### ISSUE TITLE
When i move Db to other server content dissappear

### ISSUE THREAD

**Issue by SonnySVK** [feedmeastraycat/wp-editor-widget#15]
I got this issue.

When I move content to other server - eg. from localhost deploy to live - I copy whole site to server, setup database - change home and base path. But content from widgets disappear.

Is it widgets linked to certain domain or site?

**Comment by feedmeastraycat** [comment]
I have totally missed this issue. I'm sorry about this.

Unfortunately I dont think this is related to this plugin. The plugin saves the widget data just like any other widgets. It doesnt do anything special when storing data in the database that other widgets do. (See [here](https://github.com/feedmeastraycat/wp-editor-widget/blob/master/classes/class-widget.php#L115)).

If you look in the database, the wp_options table, you can search for rows where `option_name='widget_wp_editor_widget'` to see how the widget is stored.

I havent done any tests like this in awhile, moving a site from local to deploy, with data copying. So I'm not sure why widgets wouldnt be stored. But whatever the reason Im pretty sure it is not related only to WP Editor Widget.

But if this widget is the only widget that does this, do please tell.
