### ISSUE TITLE
No ‘widget-content’ div when excluding title output

### ISSUE THREAD

**Issue by coolwebs** [feedmeastraycat/wp-editor-widget#16]
Have left a thread over at the WordPress plugins page https://wordpress.org/support/topic/no-widget-content-div-when-excluding-title-output/

Just wondering if this is an intended feature or not. I have some CSS that targets this tag/class and it disappears when excluding the title. If it's an intended feature (and you don't intend on updating this plugin much anymore) can you please let me know where I can go and edit the action/function myself?

Cheers

**Comment by feedmeastraycat** [comment]
I've responded there now :)

https://wordpress.org/support/topic/no-widget-content-div-when-excluding-title-output/#post-8465091
