### ISSUE TITLE
Update on plugin directory

### ISSUE THREAD

**Issue by Arood** [feedmeastraycat/wp-editor-widget#18]
Hello,

It seems like the plugin on WordPress Plugins directory isn't up to date: https://wordpress.org/plugins/wp-editor-widget/changelog/

**Comment by feedmeastraycat** [comment]
0.5.5 is the latest "release". 0.6.0 which exists here is a work in progress with [WPML support](https://github.com/feedmeastraycat/wp-editor-widget/issues/17).

**Comment by Arood** [comment]
Ah I see, the reason I noticed however is that I needed access to some hooks like wp_editor_widget_form that aren't available on 0.5.5.

**Comment by feedmeastraycat** [comment]
Yeah, this is a new filter. :) But I think you could run with master by downloading it here. I think it will be a 0.6.0 release pretty much without any changes. I just feel I havent tested it fully yet with the WPML support which is why I havent published it to WordPress.org yet.
