### ISSUE TITLE
set a larger editor height

### ISSUE THREAD

**Issue by cfoellmann** [feedmeastraycat/wp-editor-widget#3]
I am not sure how to but it would be nice if the editor would be initiated with a larger heigth

**Comment by RMDWebDesign** [comment]
Bit of a hack, but I seem to have worked around this by adding this to line 38 
(after `this.setEditorContent(contentId);`) of js/admin.js:

`jQuery("#wpeditorwidget_ifr").css("height", "300px");`

Might be useful for anyone searching for a solution.

**Comment by feedmeastraycat** [comment]
@RMDWebDesign: Ah. Yeah. That might be a workaround. I'll try to get some time to test it out. Thanks!

**Comment by feedmeastraycat** [comment]
Mental note: This is fixed by using visibility: hidden instead of display: none on the editors container and overlay. Just not sure its a good idea. Have to make sure it doesnt render something weird.
